### ISSUE TITLE
Incompatible with the current version of Fusion 360?

### ISSUE THREAD

**Issue by ymilord** [jamwaffles/FusionToolTranslator#1]
When I run the script against the current release I get this...

thread 'main' panicked at 'Tool number not defined', src/main.rs:43
note: Run with `RUST_BACKTRACE=1` for a backtrace.

I have 38 tools, all have numbers. Any suggestions?

Thanks.

**Comment by jamwaffles** [comment]
Can you attach your tool file to this ticket so I can do some debugging please? I'll take a look when I have a spare minute.

**Comment by ymilord** [comment]
[F360_tools.tools.zip](https://github.com/jamwaffles/FusionToolTranslator/files/380051/F360_tools.tools.zip)

Here you go.

**Comment by jamwaffles** [comment]
I've pushed a fix. If you grab the latest code and try running it against your tool table again it should work. Thanks for reporting this issue! There's no official spec from Autodesk about the tools file format so it's difficult to cater for everyone's tool libraries.

**Comment by ymilord** [comment]
Epic! Thanks!
